### ISSUE TITLE
ERROR: Encountered corrupt package tarball

### ISSUE THREAD

**Issue by abaspinar** [Netflix/metaflow#108]
Hi, 

My step works flawlessly in local mode, but when I tried it with batch mode it failed with the message:
`/bin/sh: 1: metaflow_CleanFlow_linux-64_54816c55859cfd0f8c3c9b2e51678ce87bc33a38/bin/python: not found` 
To understand what might be the reason, I locally ran a docker image(python3:6) and ran all the commands that run on the batch side. 

I noticed when conda creating the environment, some of the packages inside `pkgs` folder were failing to install. I digged deeper into it and noticed that somehow a few tarballs were not fully copied(~80%) to s3 bucket in the beginning and therefore they were incomplete.
I manually downloaded those tarballs and they all started to work fine.
What might be the reason for these incomplete tarball uploads to s3 bucket?

Computer: `Mac OSX: 10.15.1`
Conda: `Anaconda 4.7.12`
Metaflow: `2.0.1`
List of the tarballs that have failed: `chardet-3.0.4-py36_1003.tar.bz2`, `six-1.14.0-py36_0.tar.bz2`, `setuptools-45.1.0-py36_0.tar.bz2`, `pip-20.0.2-py36_1.tar.bz2`

Example error message: ERROR: ```Encountered corrupt package tarball at /root/.aws/metaflow/conda/pkgs/setuptools-45.1.0-py36_0.tar.bz2. Conda has left it in place.  Please report this to the maintainers of your package.  For the defaults channel, please report to https://github.com/continuumio/anaconda-issues```

**Comment by savingoyal** [comment]
Thanks for reporting the issue. We should add checksums on s3 uploads to guard against this.

**Comment by abaspinar** [comment]
Hi @savingoyal,
I have added `payload_signing_enabled:True` from `botocore.config` to `boto3.client` that returns from `metaflow.metaflow_config.get_authenticated_boto3_client` thinking that it resolves this issue.

However, what I've noticed is that incomplete s3 uploads was not the real problem. Somehow, conda sometimes packages with `.tar.bz2` and sometimes with `.conda` suffixes. I checked the jsons for problematic packages under `conda-meta`.

I noticed that `fn` field ends with `.tar.bz2` , but `package_tarball_full_path` field ends with `.conda` for these cases. Metaflow uses `package_tarball_full_path` and upload them with the name `fn`. Therefore `.conda` format package is uploaded there as `.tar.bz2` package.

I've added `use_only_tar_bz2: True` inside `.condarc` file to force conda to work only with `.tar.bz2` packages and now everything works.

Do you think is there a problem with my conda installation or is this how it is? 

Is there a way to force Metaflow also works only with `.tar.bz2`. Other people might be having the issue because of the similar reason. 

Thanks.

**Comment by savingoyal** [comment]
@abaspinar Specifically to guard against this issue we set `use_only_tar_bz2` to `true` [here](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/conda/conda.py#L156).

**Comment by abaspinar** [comment]
@savingoyal It seems Metaflow is already checking for that. I still don't understand why conda used `.conda` packaging there. 

Thank you for quick response.

**Comment by savingoyal** [comment]
What were the dependencies that you were specifying?

**Comment by abaspinar** [comment]
Initial step does not have any dependencies and actually it was failing there then the second step has 
``
{"category_encoders": "2.1.0",
                "joblib": "0.14.1",
                "numpy": "1.17.3",
                "xgboost": "0.90",
                "pandas": "0.25.3",
                "regex": "2020.1.8",
                "scikit-learn": "0.22"}
``

The packages that failed were `chardet-3.0.4-py36_1003.tar.bz2`, `six-1.14.0-py36_0.tar.bz2`, `setuptools-45.1.0-py36_0.tar.bz2`, `pip-20.0.2-py36_1.tar.bz2`I am not sure why these ones were needed. 

`metaflow_CleanFlow_osx-64_54816c55859cfd0f8c3c9b2e51678ce87bc33a38` had `.tar.bz2` packaged ones, but `metaflow_CleanFlow_linux-64_54816c55859cfd0f8c3c9b2e51678ce87bc33a38` had `.conda` packages for those failing ones.

**Comment by savingoyal** [comment]
@abaspinar I wasn't able to replicate the issue. We always inject `click`, `requests` and `boto3` as dependencies in the conda environment (they are needed for metaflow runtime to work inside the conda environment). So the dependencies that you are seeing are transitive dependencies of these. I have published PR #109 to verify uploads and guard them against corruption.

**Comment by jaysonpryde** [comment]
is the "*/bin/python: not found" issue already resolved? I am encountering the same error just now

**Comment by savingoyal** [comment]
@jaysonpryde PR #109 is kinda redundant because [S3 never adds partial objects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html). Let me do some more digging around possible causes.

**Comment by jaysonpryde** [comment]
@savingoyal thanks a lot. Kindly let me/us know what the solution is. still the error is still recurring even if I do a fresh install of both metaflow and the entire cloud formation

**Comment by savingoyal** [comment]
In addition to fresh install, can you also remove the .metaflow folder (it’s located in the same folder as the flow or one of the parent folder).

**Comment by jaysonpryde** [comment]
you meant the one with the config.json?

**Comment by savingoyal** [comment]
Ah no, there is another .metaflow folder that keeps track of flow specific metadata.

**Comment by jaysonpryde** [comment]
hmmm... I will look for it. But can you kindly give me a common default location for this? what i'm doing, (since i also don't know how to flush metaflow's cache) is rename the name of the flow in the script (i.e the class name)

**Comment by savingoyal** [comment]
The default location is the same folder as your flow. We reuse the folder if we find another in a parent directory (pretty similar to how .git folder works)

**Comment by benjaminbluhm** [comment]
Thanks for addressing this issue, I am facing the same problem. Removing the .metaflow folder does not solve the problem for me. For now I will add `os.system('pip install my_package')` to the step function. Hope there will be a workaround/solution to this problem.

**Comment by jaysonpryde** [comment]
@benjaminbluhm on 'pip install my_package', is my_package your flow (i.e. name of the class in the python file)? thanks

**Comment by benjaminbluhm** [comment]
@jaysonpryde Not exactly, the flow would look something like this when you use os.system('pip install ...') inside the step function. Take a look at the [documentation](https://docs.metaflow.org/metaflow/dependencies).

```
    @step
    def start(self):

        import os
        os.system('pip install pandas')
        import pandas as pd
```

**Comment by jaysonpryde** [comment]
@benjaminbluhm I see... I though this was for the "*/bin/python: not found" issue.  our concerns are different

**Comment by benjaminbluhm** [comment]
@jaysonpryde our concerns are the same. I run into exactly the same problem when I use the conda_base decorator

**Comment by jaysonpryde** [comment]
@benjaminbluhm thanks, I haven't tried you workaround yet, but it's not clear to me what does the:

`import os`
`os.system('pip install pandas`

have to do with the 

> "*bin/python: not found"

and besides, isn't that "os.sytem" call redudant considering I already placed the conda decorator:

`@conda(libraries={'pandas': '0.24.2'}`

**Comment by abaspinar** [comment]
For me the best way to debug the issue is going to Amazon ECS console and copy the commands that runs there. Afterwards, basically using the exactly the same docker image (default is `python:<python_version_major>.<python_version_minor>`) 

The real cause of the problem is difficult to regenerate and debug. The same problem happened to me with the following cases, 
1 - uploading wrong tarballs to s3 (.conda packages instead of tarball although it shouldn't)
2 - Previously messed up environment and cache (had to delete .metaflow and all the conda environments that Metaflow created.)
3 - Somehow, docker image is pointing to python3 and there is a need to create symlink to python for the initial stage where it installs awscli and downloads all the step related files from the s3.

So, it is either failing at the beginning where there is no python but instead python3 or conda environment is having problems in which you have to debug it with the way I suggested because all the commands have conda --quiet parameter set so that we don't see the real cause. 

So far, the best usage I can suggest is do not use conda and use local environment only. However, create a docker image with all the necessary dependencies (just pip is fine) and push to the ECR. Afterwards, execute metaflow with batch using that image although environment set to local. 

@savingoyal please correct or comment if my suggestions have flaws or they are misleading.

**Comment by savingoyal** [comment]
@abaspinar This is indeed helpful. Would you be open to jumping on a quick video call so that I have a better understanding of your ‘previously messed up environment’?

**Comment by abaspinar** [comment]
@savingoyal Definitely! I am pinging you from your personal github gmail account hoping that it is the way to reach out to you.

**Comment by savingoyal** [comment]
Sure my `github handle`@gmail.com works very well.

**Comment by savingoyal** [comment]
@abaspinar @jasobrown @benjaminbluhm I just opened a PR #118 which should fix this issue. 

Let me elaborate on the issue per se - Conda has two packaging formats - `.conda` and `.tar.bz2`. Currently, we can only install `.tar.bz2` packages offline - so we coax conda into downloading only `.tar.bz2` dependencies for `linux-64` architectures (even when you execute on macOS). We ship these dependencies onto s3 and download and install them on AWS Batch and execute user code within the environment thus created. To reliably generate the installation manifest as well as the specific packages we need to ship, we inspect a bunch of metadata files that conda generates while creating the environment on your laptop. For some very specific packages, in certain specific scenarios, conda fails to update the metadata information correctly, leading us to the error you have been observing. PR #118 should fix this issue. You will have to delete the `.metaflow/` directory and delete the `s3://bucket/metaflow/conda` s3 directory to evict the corrupt packages. If you have a sizeable deployment of metaflow and/or are unwilling to delete the s3 folder, I can point out steps to surgically isolate the affected dependencies - please let us know.

**Comment by savingoyal** [comment]
Please comment and re-open this thread if the issue persists with Metaflow 2.0.2.

**Comment by jaysonpryde** [comment]
@savingoyal and . @abaspinar metaflow 2.0.2 + deletion of .metaflow + deletion of "conda" in s3 did the trick. thanks for the help

**Comment by savingoyal** [comment]
Awesome!

**Comment by prometheusred** [comment]
@savingoyal is this error related to this issue?  This popped up today for me and another person working on two different Flows.  Is it because something got updated and somehow messed with the packaging?  My fix was to go into ./metaflow/<FlowName>/conda.dependencies and wipe it.  Then on rerunning, packages were reinstalled and everything worked.  

`2020-03-13 12:43:27.430 [155/start/634 (pid 97)] [6431d58b-53f6-4b9b-b881-12960b0dd1a4]   File "/metaflow/metaflow/datatools/s3.py", line 640, in _s3op_with_retries
2020-03-13 12:43:27.431 [155/start/634 (pid 97)] [6431d58b-53f6-4b9b-b881-12960b0dd1a4]     raise MetaflowS3NotFound(err_out)
2020-03-13 12:43:27.438 [155/start/634 (pid 97)] [6431d58b-53f6-4b9b-b881-12960b0dd1a4] metaflow.datatools.s3.MetaflowS3NotFound: s3op failed:
2020-03-13 12:43:27.438 [155/start/634 (pid 97)] [6431d58b-53f6-4b9b-b881-12960b0dd1a4] URL not found: s3://metaflow-metaflows3bucket-17wkzp8g2oi27/metaflow/conda/conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_llvm.tar.bz2/fa8d764c883a53d22ce622bea830c818/_openmp_mutex-4.5-1_llvm.tar.bz2
2020-03-13 12:43:27.439 [155/start/634 (pid 97)] Batch error:
2020-03-13 12:43:27.558 [155/start/634 (pid 97)] Task crashed. This could be a transient error. Use @retry to retry.
2020-03-13 12:43:27.559 [155/start/634 (pid 97)]
2020-03-13 12:43:28.814 [155/start/634 (pid 97)] Task failed.`
